journals:
  - ACCESS-MED/med-reviews:
      editor_team_id: 7184180
      eics:
        - rbeucher
      eic_team_name: ACCESS-MED/editors
      papers_repo: ACCESS-MED/med-recipes
      reviewers: https://bit.ly/2XC2Z9e
      reviewers_signup: https://medportal.herokuapp.com/reviewer-signup.html
      site_host: https://medportal.herokuapp.com
      doi_prefix: "10.0000"
      journal_alias: access-med
      journal_launch_date: '2023-01-01'
      journal_issn: '0000-0000'
      site_name: ACCESS MED-Portal
      donate_url: https://numfocus.org/donate-to-joss
      site_api_key: <%= ENV['MEDOC_API_KEY'] %>
      crossref_username: <%= ENV['CROSSREF_USERNAME'] %>
      crossref_password: <%= ENV['CROSSREF_PASSWORD'] %>
      twitter_consumer_key: <%= ENV['MEDOC_TWITTER_CONSUMER_KEY'] %>
      twitter_consumer_secret: <%= ENV['MEDOC_TWITTER_CONSUMER_SECRET'] %>
      twitter_access_token: <%= ENV['MEDOC_TWITTER_ACCESS_TOKEN'] %>
      twitter_access_token_secret: <%= ENV['MEDOC_TWITTER_ACCESS_TOKEN_SECRET'] %>
