journals:
  - ACCESS-MED/med-reviews-testing:
      editor_team_id: 7184180
      eics:
        - rbeucher
      papers: ACCESS-MED/med-recipes-testing
      reviewers: https://bit.ly/2XC2Z9e
      reviewers_signup: https://medportal.herokuapp.com/reviewer-signup.html
      site_host: https://medportal.herokuapp.com
      doi_prefix: "10.0000"
      journal_alias: access-med
      journal_launch_date: '2023-01-01'
      journal_issn: '0000-0000'
      site_name: ACCESS MED-Portal
      donate_url: https://numfocus.org/donate-to-joss
      site_api_key: <%= ENV['MEDOC_API_KEY'] %>
