journals:
  - openjournals/joss-reviews:
      editor_team_id: 2009411
      papers: openjournals/joss-papers
      reviewers: https://bit.ly/joss-reviewers
      reviewers_signup: http://joss.theoj.org/reviewer-signup.html
      site_host: http://joss.theoj.org
      doi_prefix: 10.21105
      doi_journal: joss
      site_name: Journal of Open Source Software
      donate_url: https://www.flipcause.com/secure/cause_pdetails/Mjk3Nzk=
      site_api_key: <%= ENV['JOSS_API_KEY'] %>

  - openjournals/jose-reviews:
      editor_team_id: 2414911
      papers: openjournals/jose-papers
      # TODO: Create this spreadsheet or equivalent
      reviewers: https://bit.ly/jose-reviewers
      reviewers_signup: http://jose.theoj.org/reviewer-signup.html
      site_host: https://jose.theoj.org
      doi_prefix: 10.21105
      doi_journal: jose
      site_name: Journal of Open Source Education
      donate_url: https://www.flipcause.com/secure/cause_pdetails/Mjk3ODA=
      site_api_key: <%= ENV['JOSE_API_KEY'] %>

  - openjournals/joss-reviews-testing:
      editor_team_id: 2009411
      papers: openjournals/joss-papers-testing
      reviewers: "http://staging.joss.theoj.org/reviewer-signup.html"
      site_host: http://staging.joss.theoj.org
      doi_prefix: 10.21105
      doi_journal: joss
      site_name: Journal of Open Source Software Testing
      donate_url: http://example.com
      site_api_key: <%= ENV['JOSS_API_KEY_TESTING'] %>
