name: Tests

on: [push, pull_request]
jobs:
  test:
    runs-on: ubuntu-latest
    continue-on-error: ${{ matrix.failure-allowed }}
    strategy:
      matrix:
        ruby-version: ['2.4.1', '2.7.4', '3.0.2']
        failure-allowed: [true]
        include:
        - ruby-version: '2.6.6'
          failure-allowed: false
    steps:
    - uses: actions/checkout@v2
    - name: Set up Ruby
      uses: ruby/setup-ruby@v1
      with:
        ruby-version: ${{ matrix.ruby-version }}
        bundler-cache: true
    - name: Run tests
      run: |
        ruby -v
        bundle exec rspec
